type ItemDataType = {
  Imagekey: string;
  ImageUrl: string;
  Description: string;
  ItemSize: string;
  ItemType: string;
  Amount: string;
  Stock: number;
  Branch: string;
};

export const ItemData: ItemDataType[] = [
  {
    Imagekey: 'place_image',
    ImageUrl: 'https//placw_img',
    Description: 'Fresh fresh...',
    ItemSize: 'Small',
    ItemType: 'Fish',
    Amount: '$50',
    Stock: 100,
    Branch: 'Kubwa_branch',
  },
  {
    Imagekey: 'place_image',
    ImageUrl: 'https//placw_img',
    Description: 'Fresh fresh...',
    ItemSize: 'Small',
    ItemType: 'Fish',
    Amount: '$50',
    Stock: 100,
    Branch: 'Kubwa_branch',
  },
  {
    Imagekey: 'place_image',
    ImageUrl: 'https//placw_img',
    Description: 'Fresh fresh...',
    ItemSize: 'Small',
    ItemType: 'Fish',
    Amount: '$50',
    Stock: 100,
    Branch: 'Kubwa_branch',
  },
  {
    Imagekey: 'place_image',
    ImageUrl: 'https//placw_img',
    Description: 'Fresh fresh...',
    ItemSize: 'Small',
    ItemType: 'Fish',
    Amount: '$50',
    Stock: 100,
    Branch: 'Kubwa_branch',
  },
  {
    Imagekey: 'place_image',
    ImageUrl: 'https//placw_img',
    Description: 'Fresh fresh...',
    ItemSize: 'Small',
    ItemType: 'Fish',
    Amount: '$50',
    Stock: 100,
    Branch: 'Kubwa_branch',
  },
  {
    Imagekey: 'place_image',
    ImageUrl: 'https//placw_img',
    Description: 'Fresh fresh...',
    ItemSize: 'Small',
    ItemType: 'Fish',
    Amount: '$50',
    Stock: 100,
    Branch: 'Kubwa_branch',
  },
  {
    Imagekey: 'place_image',
    ImageUrl: 'https//placw_img',
    Description: 'Fresh fresh...',
    ItemSize: 'Small',
    ItemType: 'Fish',
    Amount: '$50',
    Stock: 100,
    Branch: 'Kubwa_branch',
  },
  {
    Imagekey: 'place_image',
    ImageUrl: 'https//placw_img',
    Description: 'Fresh fresh...',
    ItemSize: 'Small',
    ItemType: 'Fish',
    Amount: '$50',
    Stock: 100,
    Branch: 'Kubwa_branch',
  },
  {
    Imagekey: 'place_image',
    ImageUrl: 'https//placw_img',
    Description: 'Fresh fresh...',
    ItemSize: 'Small',
    ItemType: 'Fish',
    Amount: '$50',
    Stock: 100,
    Branch: 'Kubwa_branch',
  },
  {
    Imagekey: 'place_image',
    ImageUrl: 'https//placw_img',
    Description: 'Fresh fresh...',
    ItemSize: 'Small',
    ItemType: 'Fish',
    Amount: '$50',
    Stock: 100,
    Branch: 'Kubwa_branch',
  },
  {
    Imagekey: 'place_image',
    ImageUrl: 'https//placw_img',
    Description: 'Fresh fresh...',
    ItemSize: 'Small',
    ItemType: 'Fish',
    Amount: '$50',
    Stock: 100,
    Branch: 'Kubwa_branch',
  },
  {
    Imagekey: 'place_image',
    ImageUrl: 'https//placw_img',
    Description: 'Fresh fresh...',
    ItemSize: 'Small',
    ItemType: 'Fish',
    Amount: '$50',
    Stock: 100,
    Branch: 'Kubwa_branch',
  },
  {
    Imagekey: 'place_image',
    ImageUrl: 'https//placw_img',
    Description: 'Fresh fresh...',
    ItemSize: 'Small',
    ItemType: 'Fish',
    Amount: '$50',
    Stock: 100,
    Branch: 'Kubwa_branch',
  },
  {
    Imagekey: 'place_image',
    ImageUrl: 'https//placw_img',
    Description: 'Fresh fresh...',
    ItemSize: 'Small',
    ItemType: 'Fish',
    Amount: '$50',
    Stock: 100,
    Branch: 'Kubwa_branch',
  },
  {
    Imagekey: 'place_image',
    ImageUrl: 'https//placw_img',
    Description: 'Fresh fresh...',
    ItemSize: 'Small',
    ItemType: 'Fish',
    Amount: '$50',
    Stock: 100,
    Branch: 'Kubwa_branch',
  },
  {
    Imagekey: 'place_image',
    ImageUrl: 'https//placw_img',
    Description: 'Fresh fresh...',
    ItemSize: 'Small',
    ItemType: 'Fish',
    Amount: '$50',
    Stock: 100,
    Branch: 'Kubwa_branch',
  },
  {
    Imagekey: 'place_image',
    ImageUrl: 'https//placw_img',
    Description: 'Fresh fresh...',
    ItemSize: 'Small',
    ItemType: 'Fish',
    Amount: '$50',
    Stock: 100,
    Branch: 'Kubwa_branch',
  },
  {
    Imagekey: 'place_image',
    ImageUrl: 'https//placw_img',
    Description: 'Fresh fresh...',
    ItemSize: 'Small',
    ItemType: 'Fish',
    Amount: '$50',
    Stock: 100,
    Branch: 'Kubwa_branch',
  },
  {
    Imagekey: 'place_image',
    ImageUrl: 'https//placw_img',
    Description: 'Fresh fresh...',
    ItemSize: 'Small',
    ItemType: 'Fish',
    Amount: '$50',
    Stock: 100,
    Branch: 'Kubwa_branch',
  },

  // ...
];
