type UsersDataType = {
  FirstName: string;
  MiddleName: string;
  LastName: string;
  UserName: string;
  Branch: string;
  Role: string;
  ID: string;
  Phone: number;
  Email: string;
};

export const UsersData: UsersDataType[] = [
  {
    FirstName: 'Mustapha',
    MiddleName: 'Hussaini',
    LastName: 'Shuaibu',
    UserName: 'Planner',
    Branch: 'kano',
    Role: 'Admin',
    ID: '728ed52f',
    Phone: 8484657657,
    Email: 'm@example.com',
  },
  {
    FirstName: 'Mustapha',
    MiddleName: 'Hussaini',
    LastName: 'Shuaibu',
    UserName: 'Planner',
    Branch: 'kano',
    Role: 'Admin',
    ID: '728ed52f',
    Phone: 8484657657,
    Email: 'm@example.com',
  },
  {
    FirstName: 'Mustapha',
    MiddleName: 'Hussaini',
    LastName: 'Shuaibu',
    UserName: 'Planner',
    Branch: 'kano',
    Role: 'Admin',
    ID: '728ed52f',
    Phone: 8484657657,
    Email: 'm@example.com',
  },
  {
    FirstName: 'Mustapha',
    MiddleName: 'Hussaini',
    LastName: 'Shuaibu',
    UserName: 'Planner',
    Branch: 'kano',
    Role: 'Admin',
    ID: '728ed52f',
    Phone: 8484657657,
    Email: 'm@example.com',
  },
  {
    FirstName: 'Mustapha',
    MiddleName: 'Hussaini',
    LastName: 'Shuaibu',
    UserName: 'Planner',
    Branch: 'kano',
    Role: 'Admin',
    ID: '728ed52f',
    Phone: 8484657657,
    Email: 'm@example.com',
  },
  {
    FirstName: 'Mustapha',
    MiddleName: 'Hussaini',
    LastName: 'Shuaibu',
    UserName: 'Planner',
    Branch: 'kano',
    Role: 'Admin',
    ID: '728ed52f',
    Phone: 8484657657,
    Email: 'm@example.com',
  },
  {
    FirstName: 'Mustapha',
    MiddleName: 'Hussaini',
    LastName: 'Shuaibu',
    UserName: 'Planner',
    Branch: 'kano',
    Role: 'Admin',
    ID: '728ed52f',
    Phone: 8484657657,
    Email: 'm@example.com',
  },
  {
    FirstName: 'Mustapha',
    MiddleName: 'Hussaini',
    LastName: 'Shuaibu',
    UserName: 'Planner',
    Branch: 'kano',
    Role: 'Admin',
    ID: '728ed52f',
    Phone: 8484657657,
    Email: 'm@example.com',
  },
  {
    FirstName: 'Mustapha',
    MiddleName: 'Hussaini',
    LastName: 'Shuaibu',
    UserName: 'Planner',
    Branch: 'kano',
    Role: 'Admin',
    ID: '728ed52f',
    Phone: 8484657657,
    Email: 'm@example.com',
  },
  {
    FirstName: 'Mustapha',
    MiddleName: 'Hussaini',
    LastName: 'Shuaibu',
    UserName: 'Planner',
    Branch: 'kano',
    Role: 'Admin',
    ID: '728ed52f',
    Phone: 8484657657,
    Email: 'm@example.com',
  },
  {
    FirstName: 'Mustapha',
    MiddleName: 'Hussaini',
    LastName: 'Shuaibu',
    UserName: 'Planner',
    Branch: 'kano',
    Role: 'Admin',
    ID: '728ed52f',
    Phone: 8484657657,
    Email: 'm@example.com',
  },
  {
    FirstName: 'Mustapha',
    MiddleName: 'Hussaini',
    LastName: 'Shuaibu',
    UserName: 'Planner',
    Branch: 'kano',
    Role: 'Admin',
    ID: '728ed52f',
    Phone: 8484657657,
    Email: 'm@example.com',
  },
  {
    FirstName: 'Mustapha',
    MiddleName: 'Hussaini',
    LastName: 'Shuaibu',
    UserName: 'Planner',
    Branch: 'kano',
    Role: 'Admin',
    ID: '728ed52f',
    Phone: 8484657657,
    Email: 'm@example.com',
  },
  {
    FirstName: 'Mustapha',
    MiddleName: 'Hussaini',
    LastName: 'Shuaibu',
    UserName: 'Planner',
    Branch: 'kano',
    Role: 'Admin',
    ID: '728ed52f',
    Phone: 8484657657,
    Email: 'm@example.com',
  },
  {
    FirstName: 'Mustapha',
    MiddleName: 'Hussaini',
    LastName: 'Shuaibu',
    UserName: 'Planner',
    Branch: 'kano',
    Role: 'Admin',
    ID: '728ed52f',
    Phone: 8484657657,
    Email: 'm@example.com',
  },
  {
    FirstName: 'Mustapha',
    MiddleName: 'Hussaini',
    LastName: 'Shuaibu',
    UserName: 'Planner',
    Branch: 'kano',
    Role: 'Admin',
    ID: '728ed52f',
    Phone: 8484657657,
    Email: 'm@example.com',
  },
  {
    FirstName: 'Mustapha',
    MiddleName: 'Hussaini',
    LastName: 'Shuaibu',
    UserName: 'Planner',
    Branch: 'kano',
    Role: 'Admin',
    ID: '728ed52f',
    Phone: 8484657657,
    Email: 'm@example.com',
  },
  {
    FirstName: 'Mustapha',
    MiddleName: 'Hussaini',
    LastName: 'Shuaibu',
    UserName: 'Planner',
    Branch: 'kano',
    Role: 'Admin',
    ID: '728ed52f',
    Phone: 8484657657,
    Email: 'm@example.com',
  },

  // ...
];
